version: "3.3"
services:
  db:
    image: postgres:11
    restart: always
    container_name: seubarriga_db
    environment:
      - POSTGRES_DB=seubarriga_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  node-ts-optimized:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: example-web-server
    volumes:
      - ./src:/app/src
    ports:
      - "8080:3001"
      - "8181:8181"
    command: yarn dev

  